### ISSUE TITLE
Recursing high level directories

### ISSUE THREAD

**Issue by nerdstein** [EvanLovely/plugin-twig-namespaces#2]
I have the following directory structure:

```
source
-- patterns
-- -- 01-atoms
-- -- -- atom1 
             -- atom1.twig
-- -- -- atom2
             -- atom2.twig
```

This requires me to define the following in config.yml:
```
namespaces:
      atoms:
        paths:
          - source/_patterns/01-atoms/01-list-title
          - source/_patterns/01-atoms/02-list-body
```

I was wondering if it was possible to only define one path, e.g. `source/_patterns/01-atoms` and have it recursively search for twig files in subdirectories?
